## Numpy array operations

In [2]:
import numpy as np

## indexing and slicing

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("Basic Slicing :", arr[3:8])
print("With Steps :", arr[1:8:2])
print("Negative indexing :", arr[-5])



Basic Slicing : [4 5 6 7 8]
With Steps : [2 4 6 8]
Negative indexing : 5


In [5]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific element :", arr_2d[1,0])    
print("Entire row :", arr_2d[1]) 
print("Entire column :", arr_2d[:,2])                

Specific element : 4
Entire row : [4 5 6]
Entire column : [3 6 9]


## sorting

In [ ]:
unsorted = np.array([1,5,4,8,9,4,6,7,2,0,3])
print("Sorted Array :\n",np.sort(unsorted))

arr_2d_unsorted = np.array([[3,5],[1,2],[9,6]])
print("Sorted 2d_array by column :\n", np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2d_array by row :\n", np.sort(arr_2d_unsorted, axis=1))
print("Sorted 2d_array default :\n", np.sort(arr_2d_unsorted))  # no axis means sorted by row.

Sorted Array :
 [0 1 2 3 4 4 5 6 7 8 9]
Sorted 2d_array by column :
 [[1 2]
 [3 5]
 [9 6]]
Sorted 2d_array by row :
 [[3 5]
 [1 2]
 [6 9]]
Sorted 2d_array by column :
 [[3 5]
 [1 2]
 [6 9]]


## Filtering

In [ ]:
numbers = np.array([1,2,3,4,5,6,7,8,9])
even_number = numbers[numbers % 2 == 0] # we are allow to write expression also in numpy.
print("Even Numbers \n", even_number)

Even Numbers 
 [2 4 6 8]


## Filter with Mask 

In [8]:
numbers = np.array([1,2,3,4,5,6,7,8,9])
mask = numbers > 5
print("Numbers greater than 5 \n", numbers[mask])

Numbers greater than 5 
 [6 7 8 9]


## Fancy Indexing VS np.where

In [10]:
numbers = np.array([1,2,3,4,5,6,7,8,9])
indices = [0,2,4,6]
print(numbers[indices])


where_result = np.where(numbers > 5)
print(where_result)
print("Numpy where \n", numbers[where_result])


[1 3 5 7]
(array([5, 6, 7, 8]),)
Numpy where 
 [6 7 8 9]


In [ ]:
condition_array = np.where(numbers > 5, numbers*3, numbers)
print(condition_array)