## Numpy array and basics

In [9]:
import numpy as np 

### creating array from list

In [10]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D_array:",arr_2d )

[1 2 3 4 5]
2D_array: [[1 2 3]
 [4 5 6]]


## python list VS numpy array

In [ ]:
# Example 1: 
py_list = [1,2,3,4,5]
print("python list :", py_list)

np_array = np.array([1,2,3,4,5]) # element wise multiplication
print("numpy array :", np_array * 2)


# Example 2: 
import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n list operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time : ", time.time() - start)

python list : [1, 2, 3, 4, 5]
numpy array : [ 2  4  6  8 10]

 list operation time:  0.13559317588806152

 Numpy operation time :  0.015325784683227539


## Creating arrays from scratch

In [ ]:
zeros_array = np.zeros((2,3))
print("Zeros array : \n", zeros_array)

ones_array = np.ones((2,3))
print("Ones Array :\n", ones_array)


full_array = np.full((2,3),9)
print("Full Array :\n", full_array)

random_array = np.random.random((2,3))
print("Random Array :\n", random_array)

sequence_array = np.arange(0,20,3)
print("sequence array : \n", sequence_array)

Zeros array : 
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array :
 [[1. 1. 1.]
 [1. 1. 1.]]
Full Array :
 [[9 9 9]
 [9 9 9]]
Random Array :
 [[0.90624597 0.31107242 0.55908404]
 [0.70180272 0.27235953 0.03791269]]
